version: "3.8"

volumes:
  db_data:

services:
  database:
    image: postgres:14.5
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: authentication
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    restart: always
  redis:
    image: redis
  app:
    build:
      context: .
    image: myapp:latest
    ports:
      - "50051:50051"
    environment:
      - USER=wesleyricardi
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - database
      - redis
